# Values below represent the number of minutes
# 1440 minutes in one day

SHORT_SEARCH_DURATION = 180
LONG_SEARCH_DURATION = 1440

# For the below queries, the search is triggered for 3 hours. This duration is based on the number (180) configured above. 
# This is done to reduce the total number of results generated by 1 single query, in case the query produces millions and millions of results that need to be fethed over the network.
# If the total duration is for 24 hours as configured in the time.json file then the below queries trigger the search for the following intervals.
# a. 00:00:00 to 03:00:00
# b. 03:00:00 to 06:00:00
# c. 06:00:00 to 09:00:00
# d. 09:00:00 to 12:00:00
# e. 12:00:00 to 18:00:00
# f. 18:00:00 to 21:00:00
# g. 21:00:00 to 00:00:00

SHORT_DURATION_QUERIES = [
    "Query1",
    "Query2",
]
